#!/bin/bash

CONDA_ENV_NAME=$1
if [ -z "$CONDA_ENV_NAME" ]; then
    echo "No conda environment given, please use a conda environment name as an argument when calling the script."
    echo "Possible conda environments:"
    conda env list
    echo 'Syntax: "source /<path>/sss_environment <conda_name>"'
    echo "ERROR"
    return 1
fi

CUSTOM_CONDA_PATH="$HOME/miniconda3"

# Load necessary modules
echo "Loading modules..."
module_list=("python/3.11.6-gcc-11.4.0" "gcc/13.2.0" "openmpi/4.1.6" "nano/7.2")
for module in "${module_list[@]}"; do
    module_name="${module%%/*}"
    if [ $(module list 2>&1 | grep "$module_name/" | wc -l) -gt 0 ]; then
        echo "    Unloaded previously loaded version of $module_name"
        module unload $module_name
    fi
    echo "    Loading $module"
    module load $module
done

# Initialize custom Conda environment
echo "Initializing Conda environment..."
if [ -f "$CUSTOM_CONDA_PATH/bin/conda" ]; then
    eval "$($CUSTOM_CONDA_PATH/bin/conda shell.bash hook)"
    if [ $? -ne 0 ]; then
        echo "Error initializing Conda."
        return 1
    fi
else
    echo "Conda not found at $CUSTOM_CONDA_PATH. Please ensure Miniconda is installed."
    return 1
fi

# Activate Conda environment
echo "Activating Conda environment..."
conda deactivate
conda activate $CONDA_ENV_NAME

# RE-ENFORCE CLUSTER MPI PATHS OVER CONDA BINARES
echo "Re-asserting system OpenMPI priorities..."
module unload openmpi/4.1.6
module load openmpi/4.1.6

# Check and install conda-build if necessary
#echo "Checking for conda-build..."
#if ! conda list conda-build &> /dev/null; then
    #echo "Installing conda-build..."
    #conda install -y conda-build
#fi

# Set environment variables

# Print message indicating environment has been loaded
echo "Serpent environment loaded."

## Force appropriate OpenMPI network transport layers based on selected partition
#if [[ "$PARTITION" == *"savio3"* ]]; then
## savio3 uses Intel Omni-Path (PSM2)
#export OMPI_MCA_mtl=psm2
#export OMPI_MCA_btl=^openib,ucx
#else
## savio2 / savio2_bigmem use Mellanox InfiniBand (UCX)
#export OMPI_MCA_pml=ucx
#export OMPI_MCA_btl=^openib,psm2
#fi
